MadLibs/MadLibs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
]

MadLibs/Main/urls.py
from django.urls import path, include
from . import views

app_name = 'Main'

urlpatterns = [
  path('', views.index, name='index'),
  path('stories/', views.stories, name='stories'),
  path('stories/<int:story_id>/', views.storyForm, name='storyForm'),
  path('results/<int:story_id>/', views.results, name='results'),
  path('addStory/', views.addStoryForm, name='addStoryForm'),
  path('addWordDescriptions/', views.addWordDescriptions, name='addWordDescriptions'),
  path('addWords/', views.addWords, name='addWords'),
]

MadLibs/Main/models.py
from django.db import models

# Create your models here.

class Story(models.Model):
  title = models.CharField(max_length=100)
  text = models.CharField(max_length=1000)
  def __str__(self):
    return self.title
  
class Word(models.Model):
  story = models.ForeignKey(Story, on_delete=models.CASCADE)
  typeOfWord = models.CharField(max_length=100)
  wordOrder = models.IntegerField()
  def __str__(self):
    return self.typeOfWord + " " + str(self.wordOrder) + " " + self.story.title

MadLibs/Main/forms.py
from django import forms
from .models import Story, Word

class StoryForm(forms.ModelForm):
  class Meta:
    model = Story
    exclude = ['title', 'text']
  def __init__(self, word_list, *args, **kwargs):
    super(StoryForm, self).__init__(*args, **kwargs)
    for word in word_list:
      self.fields[word.typeOfWord + str(word.wordOrder)] = forms.CharField(label=word.typeOfWord, max_length=100)

class AddStoryForm(forms.ModelForm):
  class Meta:
    model = Story
    fields = ['title', 'text']

class AddWordDescriptions(forms.ModelForm):
  class Meta:
    model = Word
    exclude = ['wordOrder']
  
  def __init__(self, numberOfWords, *args, **kwargs):
    super(AddWordDescriptions, self).__init__(*args, **kwargs)
    for i in range(numberOfWords - 1):
      self.fields['typeOfWord' + str(i)] = forms.CharField(label='Type of Word ' + str(i + 1), max_length=100)

MadLibs/Main/views.py
from django.shortcuts import render
from .models import Story, Word
from django.template import loader
from django.http import HttpResponse
from .forms import StoryForm, AddStoryForm, AddWordDescriptions

# Create your views here.

def index(request):
  return render(request, 'main/index.html')

def stories(request):
  story_list = Story.objects.all()
  template = loader.get_template('main/stories.html')
  return HttpResponse(template.render({'story_list': story_list}, request))

def storyForm(request, story_id):
  story = Story.objects.get(pk=story_id)
  word_list = Word.objects.filter(story=story_id).order_by('wordOrder')
  form = StoryForm(word_list)
  template = loader.get_template('main/storyForm.html')
  return HttpResponse(template.render({'story': story, 'form': form}, request))

def addStoryForm(request):
    form = AddStoryForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = AddStoryForm()
    return render(request, 'Main/addStoryForm.html', {'form': form})

def addWordDescriptions(request):
    #print(request.POST)

    storyString = request.POST.get('text')
    wordCount = storyString.count('{')

    form = AddWordDescriptions(wordCount)

    if request.method == 'POST':
        print(request.POST)
        Story.objects.create(title=request.POST.get('title'), text=request.POST.get('text'))

    if form.is_valid():
        form.save()
        form = AddWordDescriptions()
    return render(request, 'Main/addWordDescriptions.html', {'form': form})

def addWords(request):
    
    if request.method == 'POST':
      word_list = request.POST.dict()
      (k := next(iter(word_list)), word_list.pop(k))
      (k := next(iter(word_list)), word_list.pop(k))
      index = 0
      for word in word_list.values():
        Word.objects.create(story=Story.objects.last(), typeOfWord=word, wordOrder=index)
        index += 1
      print(request.POST)


    story_list = Story.objects.all()
    template = loader.get_template('main/stories.html')
    return HttpResponse(template.render({'story_list' : story_list}, request))

def results(request, story_id):
    # get the story object based on the story_id
    story = Story.objects.get(id=story_id)
    
    wordList = request.POST.dict()
    (k := next(iter(wordList)), wordList.pop(k))
    storyString = story.text.format(*wordList.values())

    context = {
        'story': story,
        'storyString': storyString,
    }
    return render(request, 'Main/story.html', context)

MadLibs/Main/templates/Main/addStoryForm.html
{% extends 'Main/base.html' %}

{% block body %}
  <div class="w-75 mx-auto">
    <h1>Add a Story</h1>
    <form action="{% url 'Main:addWordDescriptions' %}" method="POST">
      {% csrf_token %} {{form}}
      
      <button type="submit" class="btn btn-primary" >Submit</button>
    </form>
  </div>
{% endblock %}

MadLibs/Main/templates/Main/addWordDescriptions.html
{% extends 'Main/base.html' %}

{% block body %}
  <div class="w-75 mx-auto">
    <h1>Add a Story</h1>
    <form action="{% url 'Main:addWords' %}" method="POST">
      {% csrf_token %} {{form}}
      
      <button type="submit" class="btn btn-primary" >Submit</button>
    </form>
  </div>
{% endblock %}

MadLibs/Main/templates/Main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'Main/style.css' %}" type="text/css">
</head>
<body>
  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Mad Libs</a>
    <div class="navbar">
      <a class="nav-item nav-link text-light" href="{% url 'Main:index' %}">Home</a>
      <a class="nav-item nav-link text-light" href="{% url 'Main:addStoryForm' %}">Add Story</a>
    </div>
  </nav>
  
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{message.tags}}">
        {{message}}
      </div>
    {% endfor %}
  {% endif %}

  {% block body %}
  
  {% endblock %}
</body>
</html>

MadLibs/Main/templates/Main/index.html
{% extends "Main/base.html" %}

{% block body %}
<div class="w-75 mx-auto my-4">
  <h1>Welcome to Mad Libs!</h1>
  <p>Mad Libs is a phrasal template word game where one player prompts others for a list of words to substitute for blanks in a story before reading the – often comical or nonsensical – story aloud. The game is frequently played as a party game or as a pastime.</p>
  <p>Ready to play? Choose a story from our collection and get started!</p>
  <a href="{% url 'Main:stories' %}" class="btn btn-primary">Choose a Story</a>
</div>
{% endblock %}

MadLibs/Main/templates/Main/stories.html
{% extends "Main/base.html" %}

{%block body %}
  <h1 class="mt-3 w-75 mx-auto">Choose a Story</h1>
  <div class="w-75 mx-auto mt-3 d-flex flex-row flex-wrap">
    {% for story in story_list %}
      <div class="card m-2 flex-shrink-1" style="width: 400px">
        <div class="card-body">
          <h5 class="card-title">{{story.title}}</h5>
          <p class="card-text">{{story.description}}</p>
          <a href="{% url 'Main:storyForm' story.id %}" class="btn btn-primary">Play</a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

MadLibs/Main/templates/Main/story.html
{% extends 'Main/base.html' %}

{%block body %}
  <div class="w-75 mx-auto mt-3">
    <h1 class="mb-3">{{story.title}}</h1>
    {{storyString}}
  </div>
{% endblock %}

MadLibs/Main/templates/Main/storyForm.html
{% extends 'Main/base.html' %}

{% block body %}
  <div class="w-75 mx-auto align-center">
    <h1>{{story.title}}</h1>
    <form action="{% url 'Main:results' story.id%}" class="" method="POST">
      {% csrf_token %} {{form}}
      
      <button type="submit" class="btn btn-primary" >Submit</button>
    </form>
  </div>
{% endblock %}